### ISSUE TITLE
Bug - looping problem

### ISSUE THREAD

**Issue by studioyogyog** [2bt/fakesid-2#2]
I've found a weird little bug....

Start a new song and create this instrument:
![Screenshot_20200318-081228](https://user-images.githubusercontent.com/42510443/76939946-41e2a180-68f1-11ea-868d-eea5ecf2ac59.png)

Go to jam mode and it works as intended. While you hold down you get this fast high hat run type thing.

Go to create a pattern with just one note in it: it should just run for ever,right??? Until you put in another note or a --- . But no it just stops.

Thanks for a great program.

**Comment by 2bt** [comment]
Hi, sorry for responding so late. I have tried out what you said and the sound loops until `---`. Have you been able to get it working since?

**Comment by studioyogyog** [comment]
.... huh. Ive tried it again and it loops as intended. At the time I had an
old dying phone so it might have been that.

Thanks again for a really great program it's a shame there aren't more open
source apps like this for android.

Just one question though - why dya cap the speed at 4? Sometimes I might
want speed 3, 2 or even 1 - most trackers allow you to do this.

**Comment by 2bt** [comment]
Thanks, and I am glad the problem is gone.

The speed parameter is the number of video frames (i.e., 1/50 of a second) per row. Shorter rows usually don't make much sense, especially when you consider that hard restart takes up 2 frames. :shrug:

**Comment by studioyogyog** [comment]
yeah - it's not often you want 50 notes per second - but sometimes I do!
Maybe I'm an extremist.  3 is only 32nd notes or demisemiquavers at 125 bpm
... which while unusual do pop up in trap beats, and would still leave
space for the two frame reset.  Basically high speeds can be used for
trills and rolls and similar effects.  Black Midi anyone?



On Thu, 3 Dec 2020 at 14:46, Daniel Langner <notifications@github.com>
wrote:
>
> Thanks, and I am glad the problem is gone.
>
> The speed parameter is the number of video frames (i.e., 1/50 of a
second) per row. Shorter rows usually don't make much sense, especially
when you consider that hard restart takes up 2 frames. 🤷

**Comment by 2bt** [comment]
You can simulate faster notes though clever utilization of instrument wave tables and effect tables.

**Comment by studioyogyog** [comment]
Cheers!  See you soon.
