### ISSUE TITLE
How to compile for Linux?

### ISSUE THREAD

**Issue by Disonantemus** [2bt/fakesid-2#6]
I'm trying this on Android, I like it and I wish to continue the song from _smartphone into desktop_. But because the _format is not compatible_ with any other music tracker, I was thinking to compile **Fake SID** for Linux, but I'm no programmer and is not in main package respos or `AUR` (from Arch Linux), then, my attempts were unsuccessful.

From issue  #4  I understand that is possible, but I don't know how, can you give some instructions to compile in Linux? here or in the `README.md`.

In [Releases](https://github.com/2bt/fakesid/releases) there's only a Windows compiled package, nor Android (apk) or Linux.

**Comment by 2bt** [comment]
Building should be quite easy. You will have to install some packages (not sure what their names are in Arch): cmake, glm, sdl2, glew, and sndfile. Then run this:
```bash
mkdir build
cd build
cmake ..
make -j4
cd ..
ln -s build/fakesid
# then run it like so
./fakesid
```
Let me know if you're stuck.

**Comment by Disonantemus** [comment]
Sorry 4 very late repply, I'm no programmer.
I'm stuck in `cmake` step ...

### Installed:

~~~ocaml
$ pacman -Qi cmake | sed -n 2p
Version         : 3.30.3-2

$ pacman -Qi make | sed -n 2p
Version         : 4.4.1-2

$ pacman -Qi glm | sed -n 2p
Version         : 1.0.1-1

$ pacman -Qi sdl2 | sed -n 2p
Version         : 2.30.7-1

$ pacman -Qi glew | sed -n 2p
Version         : 2.2.0-7

$ pacman -Qi libsndfile | sed -n 2p
Version         : 1.2.2-2

$ paru -Qi sndfile-tools | sed -n 2p
Version         : 1.04-1
~~~

---

First I did clone the repo and then follow your steps, later I did download [tar.gz from releases](https://github.com/2bt/fakesid/archive/refs/tags/1.tar.gz).

### Cmake step error

~~~ocaml
$ cmake ..
CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- The C compiler identification is GNU 14.2.1
-- The CXX compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.1")
-- Checking for one of the modules 'glew'
-- Checking for one of the modules 'sdl2'
-- Checking for one of the modules 'sndfile'
-- Configuring done (0.5s)
CMake Error at CMakeLists.txt:7 (add_executable):
  Cannot find source file:

    src/resid-0.16/envelope.cc

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:7 (add_executable):
  No SOURCES given to target: fakesid


CMake Generate step failed.  Build files cannot be regenerated correctly.
~~~

Seems related to `resid` source.

I have `libsidplayfp` installed, that appears to have `envelope.cc` that is needed.
And same file inside [resid-0.16](http://www.zimmers.net/anonftp/pub/cbm/crossplatform/emulators/resid/index.html)
I have `GoatTracker` & [Furnace](https://github.com/tildearrow/furnace) installed (both `resid` based), and [Deflemask](https://deflemask.com) (`dSID` based).
Also found [resid-rs](https://github.com/binaryfields/resid-rs).

I tried to put `resid` files from other sources in the folder shown in error with no luck, maybe fix one file and next time is stuck in another.

---

### System:

~~~ocaml
distro: Arch Linux x86_64
kernel: 6.6.22-1-lts
shell: bash 5.2.32
term: tmux
cpu: Intel i7-4790 (8) @ 3.600GHz
~~~

**Comment by 2bt** [comment]
I am sorry, I forgot to add the resid source code files. Can you run `giit pull` and try again?

**Comment by Disonantemus** [comment]
> I am sorry, I forgot to add the resid source code files. Can you run `git pull` and try again?

Sorry, I'm no programmer and I don't know how to do `giit pull`, usually I just do `git clone` when there is no binaries or try to _follow instructions_ in **README.md**, but I can't fix any issues.

---

I did clone the repo again, and now is working!
Thank You!
